SELECT  T3.NAME,
        T3.DAYS_TO_MANUFACTURE,
        SUM(T1.ORDER_QTY) VENDAS
FROM SALES_ORDER_DETAIL AS T1
LEFT JOIN SPECIAL_OFFER_PRODUCT AS T2 ON T1.SPECIAL_OFFER_ID = T2.SPECIAL_OFFER_ID
LEFT JOIN PRODUCT AS T3 ON T2.PRODUCT_ID = T3.PRODUCT_ID
GROUP BY T3.NAME, T3.DAYS_TO_MANUFACTURE
ORDER BY VENDAS
LIMIT 3
