SELECT  T1.PERSON_ID,
        CONCAT(T1.FIRST_NAME, ' ', T1.LAST_NAME) AS NAME,
        COUNT(T1.PERSON_ID) AS PEDIDOS
FROM PERSON AS T1
LEFT JOIN CUSTOMER AS T2 ON T1.PERSON_ID = T2.PERSON_ID
LEFT JOIN SALES_ORDER_HEADER AS T3 ON T2.CUSTOMER_ID = T3.CUSTOMER_ID
WHERE T2.PERSON_ID IS NOT NULL
GROUP BY T1.PERSON_ID
ORDER BY PEDIDOS DESC
