apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: rox
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30000