SELECT  SALES_ORDER_ID,
        MONTHNAME(ORDER_DATE) AS 'MONTH',
        YEAR(ORDER_DATE) AS 'YEAR',
        TOTAL_DUE
FROM SALES_ORDER_HEADER
WHERE DATE_FORMAT(ORDER_DATE, '%%m/%%Y') = '09/2011' AND tOTAL_DUE > 1000
ORDER BY TOTAL_DUE DESC
